sudo: false
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - mvn -U clean install jacoco:report
  - mvn -U -P common-libs-only coveralls:report
